version: '3'

services:

  hw_api:
    build: .
    command: uvicorn src.api.app:app --host 0.0.0.0 --port 8009
    ports: 
      - 8009:8009
    environment:
      MONGO_CONN_STR: mongodb://admin:admin@mongo:27017
